export enum ItemType {
  CHAIR,
  COMPUTER,
  WHITEBOARD,
  VENDINGMACHINE,
  BOOKSHELF_FASHION,
  BOOKSHELF_ART,
  BOOKSHELF_SPORTS,
  BOOKSHELF_SHELTER,
  BOOKSHELF_GOURMET,
  BOOKSHELF_MOBILITY,
  BOOKLOCATION
}
